### PR TITLE
Don't run installer with /noeula argument as it will install Geforce Experience

### LINKED ISSUE #53: Cannot Disable Geforce Experience Installation
In step 2 of the driver installer: _License Agreement_, the installer gives the user the option to install either the Graphics Driver **WITH** Geforce Experience, or **WITHOUT**. 

TinyNvidiaUpdateChecker skips step 2 and selects **WITH** Geforce Experience by default when _Download + Install_ is selected. This means the only way I can update drivers without installing Geforce Experience is to extract them first then manually run the installer.

This was tested on 2 computers, one with a desktop GTX 1080 and one with a GTX 970m in optimus. Both systems are running up to date Windows 10.
image

### PR DESCRIPTION
**Pull request by henrik9999**
this fixes #53

### CODE REVIEW

**Comment by ElPumpo** [comment]
Isnt there a other argument to choose not to install geforce experience?

**Comment by henrik9999** [comment]
I didn't find one

**Comment by ElPumpo** [comment]
Ok.. Yea we'll have to remove the noeula argument but ONLY when used in quiet mode, without minimal installer enabled

**Comment by henrik9999** [comment]
this argument is used once and i removed it there which i think is where the normal install is done cuz its not possible to select not to install geforce experience because of the skip

**Comment by ElPumpo** [comment]
https://github.com/ElPumpo/TinyNvidiaUpdateChecker/commit/af010f4646dcf59d4543dd3646f39c6bc8b0192d

**Pull request closed without merging**
