### PR TITLE
fix GDPR  setup.exe error

### PR DESCRIPTION
**Pull request by cywq**
Fixes "The system cannot find the path specified."  at starting of setup.exe

### CODE REVIEW

**Comment by ElPumpo** [comment]
That wont work for everyone since the files don't exisg for all languages

**Comment by cywq** [comment]
I'm using the same method thats used in [GetLanguage()](https://github.com/ElPumpo/TinyNvidiaUpdateChecker/blob/master/TinyNvidiaUpdateChecker/MainConsole.cs#L426) which result in a "other" search when the lang id is not one of the specified ones. Am I missing something, it should work without any problems.

**Comment by cywq** [comment]
Ok you are right, missed it. Will correct it shortly

**Comment by ElPumpo** [comment]
I don't like this approach, the fix I'm going to implement is simply modifying `setup.cfg`. The title of this PR is also misleading.

**Pull request closed without merging**
