### PR TITLE
Ability to install driver already downloaded driver

### PR DESCRIPTION
**Pull request by flok**
Searching for driver in directory of the tool and installing it if the computer does not have internet.

### CODE REVIEW

**Comment by ElPumpo** [comment]
I'm not sure about this exact implementation. I recall moving this function to only when automaticly being downloaded and saved in the temp folder. It's really easy to just check if the file exists, and verify its integrity - we're not comparing hashes but file size (right?)

**Comment by cywq** [comment]
I just thought it would be nice to use the tool even when you have no internet but the driver exe on ur disk. So it searched the tool directory and lists you all drivers you have and you can choose one that you want to install.

It just checks for the filename, no hashes / filesize

**Comment by ElPumpo** [comment]
Well it should check the file size if you have internet because it might be a corrupted / not a finished download file there. I just got this idea of downloading the file with another extention name like `.download` so if the application fails when downloading people wont think that it's a finished download.

I guess you want the functionality of searching of an existing driver to extract & install. Maybe I can add a command line argument for it instead?

**Comment by cywq** [comment]
yeah thats what i added. The function only triggers when `NetworkInterface.GetIsNetworkAvailable()` return `false`

**Comment by ElPumpo** [comment]
Yea sadly it's all https requests, I cannot trace them... But geforce experience is written in javascript, right? Maybe I can take a look at its source code...

**Comment by ElPumpo** [comment]
Closing 'dead' PR

**Pull request closed without merging**
