### PR TITLE
Add --dry-run parameter

### PR DESCRIPTION
**Pull request by TomKranenburg**
Bothering you again so soon @ElPumpo (:

Let me know how you feel about this one. I have a better idea of your workflow now so this one should be a little easier. Hopefully.

I'm adding the --justcheck parameter that just checks for updates to both the app and the system GPU drivers. No download or installation is carried out. 

This allows the application to fit nicely into larger ecosystems.

### CODE REVIEW

**Comment by ElPumpo** [comment]
Hi Tom you never bother me! I want all the help you can throw at the project, really!

The command line argument name is just off. Come up with something better.

Aand again you're missing the changelog

**Comment by TomKranenburg** [comment]
Wait and see if you want to add it before I add the changelog.

What do you think for the argument name? Just pick what you like I'm not fussed. Although I might rename the variable as well so it's more intuitive.

**Comment by ElPumpo** [comment]
Nah you can add the changes yourself 👓 

And yes the variable name aswell it's so confusing haha

**Comment by TomKranenburg** [comment]
I will add the changes but really you can pick it. I'm not fussed. What about "--checkupdate"?

Back at the day job now but I'll knock this out when I get home. These two parameters are really useful for building TNUC into larger scripts.

**Comment by ElPumpo** [comment]
Hi. I think you need more time for this argument name 😂

**Comment by TomKranenburg** [comment]
Can literally be anything. Go wild.

**Comment by ElPumpo** [comment]
Have you come up with a new name yet?

**Comment by TomKranenburg** [comment]
No. Please just pick one you're comfortable with.

**Comment by DetermineAbsurd** [comment]
`--dryrun` or `--dry-run` is pretty standard in name among different applications for this type of function.

**Comment by TomKranenburg** [comment]
Done.

Let me know how you feel about it.

**Comment by ElPumpo** [comment]
Tom I'm not going to lie to you that commit was super low effort you didn't even change the variable name to match.. whatever it's fixed now and will be merged and added to the next release. Thank you for your contributions to this project!

**Comment by TomKranenburg** [comment]
I can change it if you want. I am work writing code full time.

**Pull request merged**
